version: '3.7'

services:
  backend:
    volumes:
      - static:/static
      - data:/data
    build:
      context: ./backend
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
    volumes:
      - frontend:/app/build

volumes:
  static:
  data:
  frontend:
