version: '3.7'

services:
  backend:
    volumes:
      - static:/static
      - data:/data
    env_file:
      - .env
    build:
      context: ./backend
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
    volumes:
      - frontend:/app/build
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

volumes:
  static:
  data:
  frontend:
